#!/bin/bash

THRESHOLD=40
SPACE=$(df -h | grep /dev/sda3 | awk '{print $5}'| cut -d'%' -f1)
if [ $SPACE -gt $THRESHOLD ]; then
echo "Disk is almost full and current disk usage is $SPACE % and the alert threshold is $THRESHOLD %"
echo "E-mail notification was sent to vignesh.subramaniam@iopex.com"
mail -s "Disk usage alers form 10.20.201.32" vignesh.subramaniam@iopex.com <<< "Hi, disk space is almost full. kindly fix the issue ASAP IP:10.20.201.32"
else
echo "Disk is normal and the current usage is $SPACE %"
fi
